name: Release

on:
  push:
    branches: [master]

jobs:
    
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GH_PAT}}
